// ---------------------------------------------------------------------------
// Token & reward economy configuration (Phase 1 → Phase 5).
//
// All reward amounts and anti-gaming caps live here so they can be tuned
// without touching reward wiring. Tiers drive the multiplier applied to
// contributor EARN events (moderator rewards are flat per the plan).
//
// Phase 5 (6.1): rewards became live-tunable. `REWARD_CONFIG` remains the
// hardcoded fallback/defaults; `getRewardConfig()` returns the merged config
// (DB overrides on top of the defaults) with a 5-minute Redis cache. Admins
// PATCH /api/admin/economy/rewards to write an override row and invalidate
// the cache, so changes take effect without a deploy.
// ---------------------------------------------------------------------------

import { Prisma } from '@prisma/client';
import { prisma } from '../lib/prisma';
import { redis } from '../lib/redis';
import { logger } from '../lib/logger';

export const REWARD_CONFIG = {
  // AI translation actually generated by a job (never cached serves).
  AI_TRANSLATION_AMOUNT: 2,
  AI_TRANSLATION_DAILY_CAP: 5,

  // Correction approved by a moderator (contributor).
  CORRECTION_APPROVED_AMOUNT: 20,
  CORRECTION_DAILY_CAP: 10,

  // Translation approved by a moderator (flat moderator reward).
  TRANSLATION_APPROVED_AMOUNT: 10,

  // Contributor (translator) reward when their translation is approved (2.2.3).
  TRANSLATOR_APPROVED_AMOUNT: 10,

  // Moderator reward for resolving a content report.
  REPORT_RESOLVED_AMOUNT: 5,

  // Penalty applied to the approving moderator when a translation approval
  // is overturned by an arbiter.
  OVERTURN_PENALTY_AMOUNT: 20,

  // Moderator reward for community governance actions (pin, lock, delete).
  COMMUNITY_MODERATION_REWARD: 5,

  // Share of each moderator reward diverted into the moderation pool.
  MOD_POOL_TAX_PERCENT: 0.05,

  // Minimum pool balance required before a distribution fires.
  MOD_POOL_DISTRIBUTE_MIN: 50,

  // Daily login base + streak bonus.
  DAILY_LOGIN_AMOUNT: 1,
  STREAK_BONUS_PER_DAY: 5,
  STREAK_BONUS_CAP: 50,

  // Reward for listening to a song to completion (once per user per day).
  DAILY_LISTEN_AMOUNT: 2,

  // Topic share.
  TOPIC_SHARE_AMOUNT: 2,
  TOPIC_SHARE_DAILY_CAP: 10,

  // Referral reward paid to the referrer when a new user signs up via their
  // code (D3: referrer +10, no friend bonus).
  REFERRAL_REWARD: 10,

  // One-time welcome bonus on first session/registration.
  WELCOME_BONUS: 10,

  // One-time bonus for completing the profile (2.2 phase 1).
  PROFILE_BONUS: 5,

  // Monthly season leaderboard bonuses for the top 3 (rank 1..3).
  SEASON_TOP3_BONUS: [50, 40, 30] as const,

  // Premium pass costs in GT (Phase 2). Packs never expire; the 7-day premium
  // pass grants time-boxed perks.
  PREMIUM_PASS_COSTS: {
    SEVEN_DAY_PREMIUM: 200,
    TRANSLATION_PACK_10: 50,
    TRANSLATION_PACK_50: 200,
  } as const,

  PREMIUM_PASS_LABELS: {
    SEVEN_DAY_PREMIUM: '7-Day Premium Pass',
    TRANSLATION_PACK_10: '10 Translation Credits',
    TRANSLATION_PACK_50: '50 Translation Credits',
  } as const,

  // Translation credits granted per pass. SEVEN_DAY_PREMIUM is the time-boxed
  // premium pass and grants no credits; the packs grant their named counts.
  PREMIUM_PASS_TRANSLATION_CREDITS: {
    SEVEN_DAY_PREMIUM: 0,
    TRANSLATION_PACK_10: 10,
    TRANSLATION_PACK_50: 50,
  } as const,

  // Referrals required to earn the REFERRAL_STAR badge.
  REFERRAL_STAR_THRESHOLD: 3,

  // Badge award thresholds (Phase 4). Evaluators live in badgeService.ts and
  // fire at the real events; every award is idempotent (unique userId+badgeType).
  BADGE_THRESHOLDS: {
    EARLY_ADOPTER_APPROVED: 1,
    TOP_TRANSLATOR_APPROVED: 10,
    CULTURE_CURATOR_CONTEXT: 5,
    COMMUNITY_HELPER_CONTRIBUTIONS: 10,
    DAILY_STREAK_7_DAYS: 7,
    GENEROUS_SUPPORTER_PURCHASES: 3,
    GUARDIAN_REPORTS: 10,
    HELPFUL_VOTER_VOTES: 50,
    FAN_FAVORITE_UPVOTES: 50,
  } as const,
} as const;

export type RewardConfig = typeof REWARD_CONFIG;

// ---------------------------------------------------------------------------
// Live-tunable reward types exposed to the admin economy dashboard.
// ---------------------------------------------------------------------------
export interface TunableRewardType {
  /** value sent in PATCH /api/admin/economy/rewards { rewardType } */
  type: string;
  label: string;
  /** EconomyConfig key that holds the reward amount */
  amountKey?: keyof RewardConfig & string;
  /** EconomyConfig key that holds the per-day earning cap */
  dailyCapKey?: keyof RewardConfig & string;
}

export const TUNABLE_REWARD_TYPES: readonly TunableRewardType[] = [
  { type: 'AI_TRANSLATION', label: 'AI Translation', amountKey: 'AI_TRANSLATION_AMOUNT', dailyCapKey: 'AI_TRANSLATION_DAILY_CAP' },
  { type: 'CORRECTION', label: 'Correction Approved', amountKey: 'CORRECTION_APPROVED_AMOUNT', dailyCapKey: 'CORRECTION_DAILY_CAP' },
  { type: 'TRANSLATION_APPROVAL', label: 'Translation Approval', amountKey: 'TRANSLATION_APPROVED_AMOUNT' },
  { type: 'TRANSLATOR_REWARD', label: 'Translator Approval Reward', amountKey: 'TRANSLATOR_APPROVED_AMOUNT' },
  { type: 'REPORT_RESOLVED', label: 'Report Resolved', amountKey: 'REPORT_RESOLVED_AMOUNT' },
  { type: 'OVERTURN_PENALTY', label: 'Overturn Penalty', amountKey: 'OVERTURN_PENALTY_AMOUNT' },
  { type: 'COMMUNITY_MODERATION', label: 'Community Moderation', amountKey: 'COMMUNITY_MODERATION_REWARD' },
  { type: 'MOD_POOL_TAX_PERCENT', label: 'Mod Pool Tax %', amountKey: 'MOD_POOL_TAX_PERCENT' },
  { type: 'MOD_POOL_DISTRIBUTE_MIN', label: 'Mod Pool Distribute Min', amountKey: 'MOD_POOL_DISTRIBUTE_MIN' },
  { type: 'DAILY_LOGIN', label: 'Daily Login', amountKey: 'DAILY_LOGIN_AMOUNT' },
  { type: 'STREAK_BONUS', label: 'Streak Bonus / Day', amountKey: 'STREAK_BONUS_PER_DAY' },
  { type: 'STREAK_BONUS_CAP', label: 'Streak Bonus Cap', amountKey: 'STREAK_BONUS_CAP' },
  { type: 'DAILY_LISTEN', label: 'Daily Listen', amountKey: 'DAILY_LISTEN_AMOUNT' },
  { type: 'TOPIC_SHARE', label: 'Topic Share', amountKey: 'TOPIC_SHARE_AMOUNT', dailyCapKey: 'TOPIC_SHARE_DAILY_CAP' },
  { type: 'REFERRAL', label: 'Referral Reward', amountKey: 'REFERRAL_REWARD' },
  { type: 'WELCOME_BONUS', label: 'Welcome Bonus', amountKey: 'WELCOME_BONUS' },
  { type: 'PROFILE_BONUS', label: 'Profile Bonus', amountKey: 'PROFILE_BONUS' },
];

export const REWARD_CONFIG_CACHE_KEY = 'economy:reward-config';
export const REWARD_CONFIG_CACHE_TTL = 5 * 60; // 5 minutes

async function safeRedisOp<T>(label: string, fn: () => Promise<T>, fallback: T): Promise<T> {
  try {
    return await fn();
  } catch (err) {
    logger.warn({ err, label }, `Redis ${label} failed — using fallback`);
    return fallback;
  }
}

/** Drop the cached merged config so the next read picks up DB overrides. */
export async function flushRewardConfigCache(): Promise<void> {
  await safeRedisOp('flush reward config', () => redis.del(REWARD_CONFIG_CACHE_KEY), 0);
}

/**
 * Merged reward config: hardcoded defaults overridden by any EconomyConfig
 * rows. Cached for 5 minutes; PATCH invalidates it for a live update.
 */
export async function getRewardConfig(): Promise<RewardConfig> {
  const cached = await safeRedisOp('get reward config', () => redis.get(REWARD_CONFIG_CACHE_KEY), null);
  if (cached) {
    try {
      return JSON.parse(cached) as RewardConfig;
    } catch (err) {
      logger.warn({ err }, 'Cached reward config is corrupt — reloading');
    }
  }

  let overrides: Array<{ key: string; value: unknown }> = [];
  try {
    overrides = await prisma.economyConfig.findMany({
      select: { key: true, value: true },
    });
  } catch (err) {
    // DB missing / cold-starting — fall back to hardcoded defaults.
    logger.warn({ err }, 'EconomyConfig read failed — using hardcoded defaults');
  }

  const merged = { ...REWARD_CONFIG } as Record<string, unknown>;
  for (const row of overrides) {
    if (Object.prototype.hasOwnProperty.call(REWARD_CONFIG, row.key)) {
      merged[row.key] = row.value;
    }
  }

  const result = merged as RewardConfig;

  await safeRedisOp('set reward config', () =>
    redis.set(REWARD_CONFIG_CACHE_KEY, JSON.stringify(result), 'EX', REWARD_CONFIG_CACHE_TTL),
    undefined,
  );

  return result;
}

/**
 * Persist a live override for a single config key and invalidate the cache.
 * Missing rows are created; stale rows are updated. Idempotent by `key`.
 */
export async function updateRewardConfigValue(
  key: keyof RewardConfig,
  value: number | number[] | boolean,
  adminId?: string,
  description?: string,
): Promise<{ previousValue: unknown; newValue: unknown }> {
  const previous = await prisma.economyConfig.findUnique({ where: { key } });

  await prisma.economyConfig.upsert({
    where: { key },
    update: {
      value: value as Prisma.InputJsonValue,
      lastModifiedBy: adminId ?? null,
      lastModifiedAt: new Date(),
      ...(description ? { description } : {}),
    },
    create: {
      key,
      value: value as Prisma.InputJsonValue,
      lastModifiedBy: adminId ?? null,
      description: description ?? null,
    },
  });

  await flushRewardConfigCache();

  return {
    previousValue: previous?.value ?? REWARD_CONFIG[key],
    newValue: value,
  };
}

export interface TierConfig {
  tier: 'LISTENER' | 'SCRIBE' | 'MASTER_TRANSLATOR';
  threshold: number;
  multiplier: number;
}

export const TIER_CONFIG: readonly TierConfig[] = [
  { tier: 'LISTENER', threshold: 0, multiplier: 1.0 },
  { tier: 'SCRIBE', threshold: 5, multiplier: 1.2 },
  { tier: 'MASTER_TRANSLATOR', threshold: 50, multiplier: 1.5 },
] as const;

export const resolveTier = (approvedCount: number): TierConfig => {
  let current = TIER_CONFIG[0];
  for (const config of TIER_CONFIG) {
    if (approvedCount >= config.threshold) current = config;
  }
  return current;
};