// ---------------------------------------------------------------------------
// Token & reward economy configuration (Phase 1).
//
// All reward amounts and anti-gaming caps live here so they can be tuned
// without touching reward wiring. Tiers drive the multiplier applied to
// contributor EARN events (moderator rewards are flat per the plan).
// ---------------------------------------------------------------------------

export const REWARD_CONFIG = {
  // AI translation actually generated by a job (never cached serves).
  AI_TRANSLATION_AMOUNT: 2,
  AI_TRANSLATION_DAILY_CAP: 5,

  // Correction approved by a moderator (contributor).
  CORRECTION_APPROVED_AMOUNT: 20,
  CORRECTION_DAILY_CAP: 10,

  // Translation approved by a moderator (flat moderator reward).
  TRANSLATION_APPROVED_AMOUNT: 10,

  // Moderator reward for resolving a content report.
  REPORT_RESOLVED_AMOUNT: 5,

  // Penalty applied to the approving moderator when a translation approval
  // is overturned by an arbiter.
  OVERTURN_PENALTY_AMOUNT: 20,

  // Moderator reward for community governance actions (pin, lock, delete).
  COMMUNITY_MODERATION_REWARD: 5,

  // Share of each moderator reward diverted into the moderation pool.
  MOD_POOL_TAX_PERCENT: 0.05,

  // Minimum pool balance required before a distribution fires.
  MOD_POOL_DISTRIBUTE_MIN: 50,

  // Daily login base + streak bonus.
  DAILY_LOGIN_AMOUNT: 1,
  STREAK_BONUS_PER_DAY: 5,
  STREAK_BONUS_CAP: 50,

  // Topic share.
  TOPIC_SHARE_AMOUNT: 2,
  TOPIC_SHARE_DAILY_CAP: 10,

  // Referral reward paid to the referrer when a new user signs up via their
  // code (D3: referrer +10, no friend bonus).
  REFERRAL_REWARD: 10,

  // Monthly season leaderboard bonuses for the top 3 (rank 1..3).
  SEASON_TOP3_BONUS: [50, 40, 30] as const,

  // Referrals required to earn the REFERRAL_STAR badge.
  REFERRAL_STAR_THRESHOLD: 3,

  // Badge award thresholds (Phase 4). Evaluators live in badgeService.ts and
  // fire at the real events; every award is idempotent (unique userId+badgeType).
  BADGE_THRESHOLDS: {
    EARLY_ADOPTER_APPROVED: 1,
    TOP_TRANSLATOR_APPROVED: 10,
    CULTURE_CURATOR_CONTEXT: 5,
    COMMUNITY_HELPER_CONTRIBUTIONS: 10,
    DAILY_STREAK_7_DAYS: 7,
    GENEROUS_SUPPORTER_PURCHASES: 3,
    GUARDIAN_REPORTS: 10,
    HELPFUL_VOTER_VOTES: 50,
    FAN_FAVORITE_UPVOTES: 50,
  } as const,
} as const;

export interface TierConfig {
  tier: 'LISTENER' | 'SCRIBE' | 'MASTER_TRANSLATOR';
  threshold: number;
  multiplier: number;
}

export const TIER_CONFIG: readonly TierConfig[] = [
  { tier: 'LISTENER', threshold: 0, multiplier: 1.0 },
  { tier: 'SCRIBE', threshold: 5, multiplier: 1.2 },
  { tier: 'MASTER_TRANSLATOR', threshold: 50, multiplier: 1.5 },
] as const;

export const resolveTier = (approvedCount: number): TierConfig => {
  let current = TIER_CONFIG[0];
  for (const config of TIER_CONFIG) {
    if (approvedCount >= config.threshold) current = config;
  }
  return current;
};
